name: publish Ardalis.ListStartupServices to nuget
on:
  push:
    branches: 
      - main
    paths:
      - 'src/Ardalis.ListStartupServices/**'
    
jobs:
  publish:
    name: list Ardalis.ListStartupServices on nuget.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      
      - name: public on version change
        uses: rohith/public-nuget@v2
        with:
         PROJECT_FILE_PATH: src/Ardalis.ListStartupServices/Ardalis.ListStartupServices.csproj # Relative to the repository root
         VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
         TAG_COMMIT: true # Flag to enable / disable git tagging
         TAG_FORMAT: ListStartupServices-v* # Format of the git tag, [*] gets replaced with version
         NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget API key
         
